subreddit: ["aws", "bikinibottomtwitter", "BlackPeopleTwitter", "WhitePeopleTwitter", "news", "ProgrammerHumor", "technology", "worldsnews"]  # or whatever subreddits you want to monitor
post_type: "new"    # or "hot", "top", etc
kafka_host: "kafka" # your kafka hostname
debug: true
spark_host: "spark-master"
bucket: "reddit-streaming-stevenhurwitt-2"
extra_jar_list: "org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.2,org.apache.hadoop:hadoop-common:3.3.4,org.apache.hadoop:hadoop-aws:3.3.4,org.apache.hadoop:hadoop-client:3.3.4,io.delta:delta-core_2.12:2.3.0,org.postgresql:postgresql:9.4.1212"
